### ISSUE TITLE
Unresolved dependency on shell32 on windows

### ISSUE THREAD

**Issue by retep998** [sgrif/pq-sys#24]
A user was reporting this error recently: `libpq.lib(fe-connect.c.obj) : error LNK2019: unresolved external symbol __imp_SHGetFolderPathA referenced in function getPgPassFilename`

Considering `libstd` recently got rid of its shell32 dependency, this means that crates which assumed the existence of shell32 will now have to explicitly link to shell32. Likely just adding in a line for shell32 to the vcpkg function in the build script should be enough.

**Comment by aloucks** [comment]
Can we get a patch release that includes the fix in #26?
