### ISSUE TITLE
Vcpkg support uses deprecated functions which don't work correctly

### ISSUE THREAD

**Issue by Diggsey** [sgrif/pq-sys#41]
The Vcpkg code should look like this:

```rust
#[cfg(target_env = "msvc")]
fn configured_by_vcpkg() -> bool {
    vcpkg::find_package("libpq")
        .map(|_| {
            // found libpq which depends on openssl
            vcpkg::Config::new().find_package("openssl").ok();

            println!("cargo:rustc-link-lib=crypt32");
            println!("cargo:rustc-link-lib=gdi32");
            println!("cargo:rustc-link-lib=user32");
            println!("cargo:rustc-link-lib=secur32");
        })
        .is_ok()
}
```

This ensures that *all* of the postgres and openssl static libraries are passed to the linker. Without this change, you'll get confusing linker errors when using Vcpkg.

**Comment by weiznich** [comment]
Might be related to #23? If yes I would prefer that PR (at least if someone verifies that it works correctly). Otherwise PR's to fix this are welcome. I cannot really do that, as I do not own a windows machine.

**Comment by Diggsey** [comment]
Ah yes, I did't realise `vcpkg` would also handle dependencies - I was just trying to fix the library names, but that is very nice. I'm testing that PR now.

**Comment by Diggsey** [comment]
Yes, I tested that branch and it fixed the unresolved symbols. As you can see the build script output correctly links *all* the required postgres and openssl libraries:
```
cargo:rerun-if-env-changed=PQ_LIB_DIR
cargo:rerun-if-env-changed=PQ_LIB_STATIC
cargo:rerun-if-env-changed=TARGET
cargo:rustc-link-search=native=[redacted]\vcpkg\installed\x64-windows-static-md\lib
cargo:rustc-link-lib=libecpg
cargo:rustc-link-lib=libecpg_compat
cargo:rustc-link-lib=libpgcommon
cargo:rustc-link-lib=libpgport
cargo:rustc-link-lib=libpgtypes
cargo:rustc-link-lib=libpq
cargo:rustc-link-lib=zlib
cargo:rustc-link-lib=libssl
cargo:rustc-link-lib=libcrypto
cargo:rustc-link-lib=lz4
cargo:rustc-link-lib=crypt32
cargo:rustc-link-lib=gdi32
cargo:rustc-link-lib=user32
cargo:rustc-link-lib=secur32
cargo:rustc-link-lib=shell32
```
