### ISSUE TITLE
Using `#[cfg(target_os = ...]` doesn't work in build scripts

### ISSUE THREAD

**Issue by stormshield-kg** [sgrif/pq-sys#53]
Cross-compiling `pq-src` from a Linux host to a Windows target doesn't work because of these lines : https://github.com/sgrif/pq-sys/blob/5454b4f93360a5767004e75580d3c693afb2636f/pq-src/build.rs#L181-L182

The target os is the host target in `build.rs` when cross-compiling, see cargo issue : https://github.com/rust-lang/cargo/issues/4932#issuecomment-357163633.

**Comment by weiznich** [comment]
Thanks for opening this bug report. You are right that will not work for cross compiling. Also the file list is likely broken: https://github.com/sgrif/pq-sys/blob/722f606ec35448f4e4df0978a5a14ba36345ca1f/pq-src/build.rs#L4 (see also the other `#[cfg]` a bit below).

Would you mind submitting a PR fixing these locations to use the the target provided by the environment variables set by cargo instead?

**Comment by stormshield-kg** [comment]
Yes, see #54.
