### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by golddranks** [sgrif/pq-sys#7]
With the recently added PR, it's possible to compile `diesel_cli` on Musl target just by setting three env vars: PKG_CONFIG_PATH, PKG_CONFIG_ALL_STATIC and PKG_CONFIG_ALLOW_CROSS. (Of course, `pkg-config` must be able to find installed Musl-compiled dependencies).

So, a minor version bump to this (and possibly to `diesel_cli`) be nice to be able to get it easily!

**Comment by sgrif** [comment]
Sorry for the delay

**Comment by sgrif** [comment]
Ah fuck I accidentally released without your commit. >_>

**Comment by sgrif** [comment]
Ok I've released v0.2.6 which has your changes. v0.2.5 is identical to 0.2.4 because I am dumb.
