### ISSUE TITLE
0.3.2 build fail under ubuntu 16.10

### ISSUE THREAD

**Issue by Matrix-Zhang** [sgrif/pq-sys#8]
```error:` failed to run custom build command for `pq-sys v0.3.2`
process didn't exit successfully: `/tmp/cargo-install.tld0CGuUM1C9/release/build/pq-sys-711360ba9ed09407/build-script-build` (exit code: 101)
--- stdout
/usr/include/stdio.h:33:11: fatal error: 'stddef.h' file not found, err: true

--- stderr
/usr/include/stdio.h:33:11: fatal error: 'stddef.h' file not found
thread 'main' panicked at 'Unable to generate bindings for libpq: ()', /checkout/src/libcore/result.rs:860
stack backtrace:
   1:     0x558051d00229 - std::sys::imp::backtrace::tracing::imp::write::hbb14611794d3841b
                        at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x558051d0468e - std::panicking::default_hook::{{closure}}::h6ed906c7818ac88c
                        at /checkout/src/libstd/panicking.rs:351
   3:     0x558051d04294 - std::panicking::default_hook::h23eeafbf7c1c05c3
                        at /checkout/src/libstd/panicking.rs:367
   4:     0x558051d04a8b - std::panicking::rust_panic_with_hook::hd0067971b6d1240e
                        at /checkout/src/libstd/panicking.rs:545
   5:     0x558051d04914 - std::panicking::begin_panic::h1fd1f10a3de8f902
                        at /checkout/src/libstd/panicking.rs:507
   6:     0x558051d04889 - std::panicking::begin_panic_fmt::haa043917b5d6f21b
                        at /checkout/src/libstd/panicking.rs:491
   7:     0x558051d04817 - rust_begin_unwind
                        at /checkout/src/libstd/panicking.rs:467
   8:     0x558051d3054d - core::panicking::panic_fmt::he9c7f335d160b59d
                        at /checkout/src/libcore/panicking.rs:69
   9:     0x558051a90830 - core::result::unwrap_failed::h179c8be6c16eaf7a
  10:     0x558051a95b12 - build_script_build::main::h97929f8e97a65f5d
  11:     0x558051d0ba0a - __rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:98
  12:     0x558051d05236 - std::rt::lang_start::hb7fc7ec87b663023
                        at /checkout/src/libstd/panicking.rs:429
                        at /checkout/src/libstd/panic.rs:361
                        at /checkout/src/libstd/rt.rs:57
  13:     0x7fdef04393f0 - __libc_start_main
  14:     0x558051a8fd69 - _start
  15:                0x0 - <unknown>

Build failed, waiting for other jobs to finish...
error: failed to compile `diesel_cli v0.11.0`, intermediate artifacts can be found at `/tmp/cargo-install.tld0CGuUM1C9```

**Comment by sgrif** [comment]
0.4.0 should fix your problem.
